### ISSUE TITLE
Incorrect or incomplete usage instructions with phpdoc 2.8.2

### ISSUE THREAD

**Issue by pdbogen** [evert/phpdoc-md#5]
```
pdbogen@mbp-pbogen:~/project-php$ phpdoc parse -t . -d src
Collecting files .. OK
Initializing parser .. OK
Parsing files
Parsing /home/pdbogen/project-php/src/project.php
Storing cache in "/home/pdbogen/project-php" .. OK
```

..no structure.xml is generated. Is phpdocmd totally incompatible, or is there new syntax to make phpdoc generate a structure.xml?

**Comment by evert** [comment]
Where did you find those instructions? In README.md it's this:

`phpdoc  -d [project path] -t . --template="xml"`

**Comment by evert** [comment]
Right.. it's in the binary! will fix this.

**Comment by evert** [comment]
Update to version 0.1.1. It's now fixed
