### ISSUE TITLE
Can't run phpdocmd

### ISSUE THREAD

**Issue by sciamannikoo** [evert/phpdoc-md#6]
Hi!

From what I can see, the composer.json file is fine:
```
{
  "name": "wpml/docs",
  "description": "Build Documentation from PhpDoc comments",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "license": "proprietary",
  "authors": [
    {
      "name": "OnTheGoSystems",
      "email": "email@example.com"
    }
  ],
  "require": {
    "evert/phpdoc-md": "0.1.1"
  }
}
```

`compass install` or `compass update` goes well: no errors or warning.

From the terminal:
```
$ phpdocmd
bash: phpdocmd: command not found
```

Same result if I try from a test phpcli script:
```
<?php
require 'vendor/autoload.php';

exec( 'phpdocmd' );
```

Result: `sh: phpdocmd: command not found`

Am I missing something?
I think so, since googling around I couldn't find any single case like mine.

**Comment by evert** [comment]
Make sure you specify the entire path to `phpdocmd` when running it. Are you in the `bin/` directory?

**Comment by sciamannikoo** [comment]
Damn... such a silly oversight: thanks!
