### ISSUE TITLE
Documentation is missing some important data

### ISSUE THREAD

**Issue by sciamannikoo** [evert/phpdoc-md#8]
The same projects as for #7 contains a very lights structure.xml for just one file, with this data:
- File description
- Some PHPDoc for few constant and functions

None of them gets documented.

I get an empty APIIndex.md file (if I exclude the "API Index" heading).

Apparently this script ignores all functions and generic file descriptions: am I right?

**Comment by evert** [comment]
Yes this is correct. The intent of this tool is to generate documentation for applications that strictly follow a few conventions:

* PSR-1 or PSR-4
* All code is in classes
* One class per file

I don't mind the idea of adding more options for people that need more flexibility or have a different coding standard, but it's not something I intend to add myself.

So in short: patches welcome.

I don't want to keep tickets open for things that I don't plan to do, so I'm closing this one. Hope you don't mind.
